/************************************************************************************
This is your Page Code. The appAPI.ready() code block will be executed on every page load.
For more information please visit our docs site: http://docs.crossrider.com
  
get the shops array from http://www.sponsorkliks.com/shop_names_arrays.php

datum 23 december 2012

kopieer de winkellijst van http://www.sponsorkliks.com/shop_names_arrays.php

kopieer alles dan vanaf var sites = new Array...

en plak deze op de juiste plek in de code hieronder, u dient in totaal 3 vervangingen te doen, inclusief de blokhaken:


[plak hier de winkellijst]
[vul hier uw naam in]
[vul hier uw sponsorkiksid in]

*************************************************************************************/

function getCookie(c_name)
{
	var i,x,y,ARRcookies=document.cookie.split(";");
	for (i=0;i<ARRcookies.length;i++)
  {
	  x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("="));
	  y=ARRcookies[i].substr(ARRcookies[i].indexOf("=")+1);
	  x=x.replace(/^\s+|\s+$/g,"");
	  if (x==c_name)
	  {
	    return unescape(y);
	  }
  }
  return null;
}

function setCookie(c_name,value,exhours)
{
	var now = new Date();
	var time = now.getTime();
	time += 3600 * 1000 * exhours;
	now.setTime(time);
	
	var c_value=value + "; expires="+now.toUTCString();
	
	document.cookie=c_name + "=" + c_value;
}

appAPI.ready(function($) {

namen[0] = "1-800-BASKETS.COM";
	namen[1] = "123Lens.nl";
	namen[2] = "123tijdschrift.nl";
	namen[3] = "123tuinposter.nl";
	namen[4] = "2BStores.com";
	namen[5] = "A2koi";
	namen[6] = "Accor Hotels";
	namen[7] = "Aeromeistershop.nl";
	namen[8] = "Afvallen met Nederland";
	namen[9] = "Agoda.com";
	namen[10] = "Aktiesport.nl";
	namen[11] = "AlarmSecur.com";
	namen[12] = "Albelli";
	namen[13] = "Algebeld.nl";
	namen[14] = "ALLDATAdiy.com";
	namen[15] = "Alternate";
	namen[16] = "AMOMA";
	namen[17] = "Anti-Slipcursus.nl";
	namen[18] = "ArganWinkel.nl";
	namen[19] = "Autoeurope";
	namen[20] = "AutoScout24";
	namen[21] = "AutoVendi.nl";
	namen[22] = "Auxifina";
	namen[23] = "AV-Tours";
	namen[24] = "Avantisport";
	namen[25] = "Azenda.com";
	namen[26] = "Baby-schoenen.nl";
	namen[27] = "Babygoodies";
	namen[28] = "Badjasparadijs";
	namen[29] = "Badkamerexclusief.nl";
	namen[30] = "Badkamertelevisie.nl";
	namen[31] = "Badkamerwarenhuis.nl";
	namen[32] = "Bagazoo.com";
	namen[33] = "Balanceergewicht.nl";
	namen[34] = "Banggood.com";
	namen[35] = "Barbecueshop.nl";
	namen[36] = "Barista Italiano";
	namen[37] = "Barse.com";
	namen[38] = "Basiclabel.nl";
	namen[39] = "Bax";
	namen[40] = "Bbqengourmet.nl";
	namen[41] = "BBQwinQel.nl";
	namen[42] = "BeauViCa.nl";
	namen[43] = "bebe.com";
	namen[44] = "Beconfident.nl";
	namen[45] = "Bedden.nl";
	namen[46] = "BedGarant";
	namen[47] = "Bedrijfsplantraining.nl";
	namen[48] = "Beeldenmarkt.nl";
	namen[49] = "NMBS";
	namen[50] = "Beliani.nl";
	namen[51] = "Bellatio";
	namen[52] = "Ben";
	namen[53] = "BestBuyHoesjes.nl";
	namen[54] = "Beste-Dekbed.nl";
	namen[55] = "Bestecanvas.nl";
	namen[56] = "Bestel-verf.nl";
	namen[57] = "Betersport.nl";
	namen[58] = "bfdeals.com";
	namen[59] = "BidHere.com";
	namen[60] = "Biedbazaar";
	namen[61] = "Bigandbag.com";
	namen[62] = "BigBank";
	namen[63] = "BigBrands.be";
	namen[64] = "Bigfreddy.com";
	namen[65] = "BigMoneyScratch.com";
	namen[66] = "Biotuinkassen.nl";
	namen[67] = "Bloembollenkopen.nl";
	namen[68] = "Blokker";
	namen[69] = "bobex.be België";
	namen[70] = "Bodylab.nl";
	namen[71] = "Bodystore.nl";
	namen[72] = "BoeketCadeau.nl";
	namen[73] = "BoFashion";
	namen[74] = "bol.com";
	namen[75] = "Bongo";
	namen[76] = "BonPrix";
	namen[77] = "Booking.com";
	namen[78] = "BoumanOnline";
	namen[79] = "Brandos.be";
	namen[80] = "Breakloose.be";
	namen[81] = "BrentHaven.com";
	namen[82] = "Brinic Toys";
	namen[83] = "Brunotti";
	namen[84] = "Budgetparket BE";
	namen[85] = "BullGuard.com";
	namen[86] = "Bungalows.nl";
	namen[87] = "butterflyphoto.com";
	namen[88] = "BuyMounts.com";
	namen[89] = "BuyYourWine.com";
	namen[90] = "Cadeautjes.nl";
	namen[91] = "Campusshop.nl";
	namen[92] = "Canvasscherm.nl";
	namen[93] = "Canvaswinkel.nl";
	namen[94] = "Cardstore.com";
	namen[95] = "Carnavalswinkel-online.nl";
	namen[96] = "Centralpoint";
	namen[97] = "CGEMarket.com";
	namen[98] = "ChatSim.com";
	namen[99] = "Cheaptech.nl";
	namen[100] = "CollectablesDirect.com";
	namen[101] = "Comforda.com";
	namen[102] = "CompUSA.com";
	namen[103] = "Computer Care Center";
	namen[104] = "Conrad";
	namen[105] = "Contactlenzen-optica.nl";
	namen[106] = "Cookies.com";
	namen[107] = "Coolblue";
	namen[108] = "Coolblue";
	namen[109] = "Coolshop";
	namen[110] = "Corel.com";
	namen[111] = "Corendon.be";
	namen[112] = "Costumes4Less.com";
	namen[113] = "Coupons.com";
	namen[114] = "Danajuwelier.nl";
	namen[115] = "De-boeddha-winkel.nl";
	namen[116] = "Decathlon";
	namen[117] = "Decoaction";
	namen[118] = "Dekbedovertrekkenenzo.nl";
	namen[119] = "dekbedovertrekshop.com";
	namen[120] = "Dekoria.nl";
	namen[121] = "Dekroo";
	namen[122] = "Delivery.com";
	namen[123] = "Dell";
	namen[124] = "Denksport";
	namen[125] = "DennisDeal";
	namen[126] = "Denvin";
	namen[127] = "DeOnlineDrogist.nl";
	namen[128] = "Deroofvisser.com";
	namen[129] = "Designsanitairshop.nl";
	namen[130] = "Designtuinhaarden.nl";
	namen[131] = "Desigual.com";
	namen[132] = "Dimenno.nl";
	namen[133] = "Dinette.com";
	namen[134] = "Disneyland Paris BE";
	namen[135] = "dmLights";
	namen[136] = "DmLights";
	namen[137] = "DokterOnline.com";
	namen[138] = "Dollhouse.com";
	namen[139] = "Doublepoint.nl";
	namen[140] = "Douche-Concurrent.nl";
	namen[141] = "DrJays.com";
	namen[142] = "Drogisterij.net";
	namen[143] = "Dronecentraal.nl";
	namen[144] = "Drouwenerzand";
	namen[145] = "Dualbrella.nl";
	namen[146] = "DuracellDirect.com";
	namen[147] = "Dutch Designers Outlet";
	namen[148] = "E5 mode";
	namen[149] = "EasyEnergy";
	namen[150] = "Elektrische BuitenBoordMotoren";
	namen[151] = "ebookers.be";
	namen[152] = "Energiedirect.nl";
	namen[153] = "E.ON";
	namen[154] = "Essent ";
	namen[155] = "EuroFlorist.be";
	namen[156] = "Euroflorist";
	namen[157] = "Euromaster Bandenservice BV";
	namen[158] = "Eurostar";
	namen[159] = "Expedia";
	namen[160] = "Experiencegifts.be";
	namen[161] = "Expresso";
	namen[162] = "F-Secure BE";
	namen[163] = "FabulousUnderwear.nl";
	namen[164] = "Falipocandles.nl";
	namen[165] = "Farmaline";
	namen[166] = "FashionMania";
	namen[167] = "Fashionnstyle.nl";
	namen[168] = "FashionStateofMind";
	namen[169] = "Feestwinkeldirect.nl";
	namen[170] = "FergieShoes.com";
	namen[171] = "Fiets-stoeltje.nl";
	namen[172] = "Fiets-zitje.nl";
	namen[173] = "Fietskledingvoordeel.nl";
	namen[174] = "FietsUniek.nl";
	namen[175] = "Fietsweb.nl";
	namen[176] = "Fiftiesstore.com";
	namen[177] = "Fine2Sleep";
	namen[178] = "Fitbella.nl";
	namen[179] = "Fitness-Geest";
	namen[180] = "Flinndal.be";
	namen[181] = "Flixbus";
	namen[182] = "Foopla.nl";
	namen[183] = "Forza-Refurbished.nl";
	namen[184] = "Forzawielerreizen.nl";
	namen[185] = "Fotogeprint.nl";
	namen[186] = "Fotogeschenk.nl";
	namen[187] = "Fotoopaluminium.com";
	namen[188] = "FragranceX.com";
	namen[189] = "Freelancespecialisten.nl";
	namen[190] = "Friezel.nl";
	namen[191] = "FTD.com";
	namen[192] = "Fundesign.nl";
	namen[193] = "Gadgetsgift.nl";
	namen[194] = "GearBest.com";
	namen[195] = "GenericSeeds.com";
	namen[196] = "Getled";
	namen[197] = "Get your guide";
	namen[198] = "Gezondmarkt.nl";
	namen[199] = "Gitaarles";
	namen[200] = "Gloeilampgoedkoop";
	namen[201] = "Go4inkt";
	namen[202] = "Goedvuurwerk.nl";
	namen[203] = "GoParcs.nl";
	namen[204] = "GoPro-mania.nl";
	namen[205] = "Gorillasports";
	namen[206] = "Greenchoice";
	namen[207] = "Greetz";
	namen[208] = "Groupactie";
	namen[209] = "Groupon ";
	namen[210] = "Guidogear.com";
	namen[211] = "Gummil";
	namen[212] = "Haarshop";
	namen[213] = "Halfords";
	namen[214] = "Happy-Size.nl";
	namen[215] = "HappyHome.be";
	namen[216] = "HappyRainyDays";
	namen[217] = "Hardloop-Geest";
	namen[218] = "HarmanAudio.nl";
	namen[219] = "Heels.com";
	namen[220] = "Heine";
	namen[221] = "HEMA";
	namen[222] = "Hetfotoalbum.nl";
	namen[223] = "HetLaatsteTafeltje.nl";
	namen[224] = "Hockeyhuis.nl";
	namen[225] = "HockeyMonkey.com";
	namen[226] = "Hoesjescases.nl";
	namen[227] = "Hogenboom Vakantieparken";
	namen[228] = "Homefitness4You.nl";
	namen[229] = "HookedonPhonics.com";
	namen[230] = "Hostingwalk.com";
	namen[231] = "Hotelopia";
	namen[232] = "Hotelroom.com";
	namen[233] = "Hotels.com";
	namen[234] = "Hotels.nl";
	namen[235] = "HotelsClick.com";
	namen[236] = "HotelsCombined.com";
	namen[237] = "Hotelsviva.com";
	namen[238] = "HotelTravel.com";
	namen[239] = "Lodger";
	namen[240] = "Huisdierplein.nl";
	namen[241] = "Huishoudelijkcoppens.nl";
	namen[242] = "Huurstunt.nl";
	namen[243] = "Igeschenke.de ";
	namen[244] = "IkenIk";
	namen[245] = "Ikenmijnkind.nl";
	namen[246] = "Ikonic Toys";
	namen[247] = "In The Swim - InTheSwim.com";
	namen[248] = "InkCartridges.com";
	namen[249] = "Inkclub.com";
	namen[250] = "InkGarden.com";
	namen[251] = "InkjetSuperstore.com";
	namen[252] = "InkPlusToner.com";
	namen[253] = "Internet-bikes.com";
	namen[254] = "Intertoys";
	namen[255] = "InviteMe.nl";
	namen[256] = "iParts4u.nl";
	namen[257] = "Iron-Gym.nl ";
	namen[258] = "iTunes, App Store, Mac App Store and iBookstore ";
	namen[259] = "Jackz";
	namen[260] = "Jamin";
	namen[261] = "Janox";
	namen[262] = "JHP-Fashion.nl";
	namen[263] = "JJGames.com";
	namen[264] = "JM Bruneau";
	namen[265] = "Jouwsportzaak.nl";
	namen[266] = "Just4kidz.eu";
	namen[267] = "Kadogalerie.nl";
	namen[268] = "Kadopagina.nl";
	namen[269] = "Katarina.com";
	namen[270] = "Kerst-feestwinkel.nl";
	namen[271] = "Keukenaccessoiresshop.nl";
	namen[272] = "Keukenmarkt.BE";
	namen[273] = "Keukenmarkt.nl";
	namen[274] = "KimmyShop.com";
	namen[275] = "Kinderfietsen.com";
	namen[276] = "Kinderkleding-tekoop.nl";
	namen[277] = "Kinderkleding.nl";
	namen[278] = "Kixx-online.nl";
	namen[279] = "kleertjes.com";
	namen[280] = "Klingel";
	namen[281] = "KLM";
	namen[282] = "Kluizen.nl";
	namen[283] = "Kluscenter.nl";
	namen[284] = "knuffelparadijs";
	namen[285] = "Koffiebonen-bestellen.nl";
	namen[286] = "Koffiediscounter.nl";
	namen[287] = "Kozijnen-offertes.nl";
	namen[288] = "KunstgrasDirect.nl";
	namen[289] = "Kunstkerstbomen.nl";
	namen[290] = "Kunstspiegel.nl";
	namen[291] = "Kweekkast.nl";
	namen[292] = "LaminaatDirect.nl";
	namen[293] = "Lampdirect";
	namen[294] = "Lanaformwinkel.nl";
	namen[295] = "Laptop-Kopen.nl";
	namen[296] = "Laptopaccushop.nl";
	namen[297] = "Latexwaisttrainer.com";
	namen[298] = "Lecturama";
	namen[299] = "Leen Bakker";
	namen[300] = "Leesmap";
	namen[301] = "Lenseo.com ";
	namen[302] = "Lenson.nl";
	namen[303] = "Lensway.nl";
	namen[304] = "Lexa.nl";
	namen[305] = "Lichtdiscounter";
	namen[306] = "LifeStride.com";
	namen[307] = "LightInTheBox.com";
	namen[308] = "Limos.com";
	namen[309] = "LittleLegends.nl";
	namen[310] = "Living.nl";
	namen[311] = "L\'Occitane NL";
	namen[312] = "LogoSportswear.com";
	namen[313] = "LOKS";
	namen[314] = "Lopesanhotels.com";
	namen[315] = "Loungeset-express.nl";
	namen[316] = "Loungeset.nl";
	namen[317] = "Lowlens";
	namen[318] = "lulu.com";
	namen[319] = "Magix.com";
	namen[320] = "Magnalight.com";
	namen[321] = "Makeupshoppen";
	namen[322] = "Match4me";
	namen[323] = "Maxbedden.nl";
	namen[324] = "Medionshop";
	namen[325] = "Medpets.nl";
	namen[326] = "MegaGadgets.nl";
	namen[327] = "Met jou";
	namen[328] = "Meubelpootjes.nl";
	namen[329] = "MexGrocer.com";
	namen[330] = "Mexx";
	namen[331] = "Mijndomein.nl";
	namen[332] = "Mijnleesbril.nl";
	namen[333] = "MiniInTheBox.com";
	namen[334] = "MissEtam";
	namen[335] = "MJTrim.com";
	namen[336] = "Mobieltekoop.nl";
	namen[337] = "Molenheide";
	namen[338] = "Monuta";
	namen[339] = "Mooiesneakers.nl";
	namen[340] = "MooiVakanties";
	namen[341] = "Morpheus-beddengoed.nl";
	namen[342] = "Mountnutrition.nl";
	namen[343] = "Muurmode.nl";
	namen[344] = "Muurteksten";
	namen[345] = "Mwave.com";
	namen[346] = "My M&M’s";
	namen[347] = "myphotobook.nl";
	namen[348] = "Myxlshop.nl";
	namen[349] = "NA-KD";
	namen[350] = "Navabi";
	namen[351] = "NeeltjeJans.nl";
	namen[352] = "Nelly.com";
	namen[353] = "Neostrada.nl";
	namen[354] = "Netspecialist.nl";
	namen[355] = "New York Pizza";
	namen[356] = "NHA";
	namen[357] = "NHBO";
	namen[358] = "NL Energie";
	namen[359] = "NOWvitamins.nl";
	namen[360] = "NuBuiten.nl";
	namen[361] = "Nuon ";
	namen[362] = "Nuon";
	namen[363] = "Nutrivian.nl";
	namen[364] = "Nuttracker.nl";
	namen[365] = "Office Deals";
	namen[366] = "OfficeDeals.be";
	namen[367] = "Ohmygelnails.nl";
	namen[368] = "OHRA";
	namen[369] = "Oktoberfest-Winkel.nl";
	namen[370] = "One.com";
	namen[371] = "Online-sanitairkopen.nl";
	namen[372] = "Onlinedierenspeciaalzaak.nl";
	namen[373] = "Onlinejaskopen.nl";
	namen[374] = "Onlinevakantiegids";
	namen[375] = "Onlineverf.nl";
	namen[376] = "Ophang-systemen.nl";
	namen[377] = "Oranjediscounter.nl";
	namen[378] = "Oranjeshopper.nl";
	namen[379] = "Otel.com";
	namen[380] = "OTTO";
	namen[381] = "Otto\'s";
	namen[382] = "OverhemdenSales.nl";
	namen[383] = "Overtoom";
	namen[384] = "Paintballstrand.nl";
	namen[385] = "Pakketkiezer.nl";
	namen[386] = "Paradigit";
	namen[387] = "Parship ";
	namen[388] = "Parship.nl";
	namen[389] = "Partyshopper.be ";
	namen[390] = "PerfectBody.nl";
	namen[391] = "PerfectMatch.com";
	namen[392] = "Perfume.com";
	namen[393] = "Peterhahn.nl";
	namen[394] = "Philips";
	namen[395] = "Piercings.nl";
	namen[396] = "Pinhigh.nl";
	namen[397] = "Pizza.be";
	namen[398] = "Plasma-discounter";
	namen[399] = "Playseat";
	namen[400] = "PlusToys";
	namen[401] = "Plutosport";
	namen[402] = "Podobrace";
	namen[403] = "PortemonneeZ.nl";
	namen[404] = "Posters.nl";
	namen[405] = "PosterXXL";
	namen[406] = "PostNL";
	namen[407] = "Prénatal";
	namen[408] = "PrintCountry.com";
	namen[409] = "Printit";
	namen[410] = "Printvoordeelshop.nl";
	namen[411] = "Printwinkel.nl";
	namen[412] = "ProDynamictape";
	namen[413] = "Promiss";
	namen[414] = "Proxisazur.be";
	namen[415] = "Qwebwinkel.nl";
	namen[416] = "RandomBuy.com";
	namen[417] = "Refurbished.nl";
	namen[418] = "ReisXperts";
	namen[419] = "Rentalcars.com";
	namen[420] = "ReSnap.com";
	namen[421] = "Rexbo.nl";
	namen[422] = "Riemenzo.nl";
	namen[423] = "Robinson.com";
	namen[424] = "Rootz-sieraden.nl";
	namen[425] = "Runnersdate.nl";
	namen[426] = "SaferWholesale.com";
	namen[427] = "Sandaya.nl";
	namen[428] = "Sani Dream";
	namen[429] = "SchipholTickets.nl";
	namen[430] = "SchoenenTorfs.nl";
	namen[431] = "Schuurman Schoenen";
	namen[432] = "Score";
	namen[433] = "Shapewear.nl";
	namen[434] = "Shapewear.be";
	namen[435] = "Shoebuy.com";
	namen[436] = "Shoeby";
	namen[437] = "Shoemixx.be";
	namen[438] = "Shoes.com";
	namen[439] = "ShoeSteal.com";
	namen[440] = "Shop4rugzakken.nl";
	namen[441] = "Shopdistrict";
	namen[442] = "Shopies.nl";
	namen[443] = "ShopnDrop";
	namen[444] = "TOMS";
	namen[445] = "Showroomprive.nl";
	namen[446] = "SierbetonOnline.nl";
	namen[447] = "SinQel.com";
	namen[448] = "Sinterklaas-feestwinkel.nl";
	namen[449] = "SIXT";
	namen[450] = "Sjaalmania";
	namen[451] = "Skiwear4u.com";
	namen[452] = "Sky-Audio.nl";
	namen[453] = "SLAM-online.nl";
	namen[454] = "Sleepcool.nl";
	namen[455] = "Sloffen-webshop.nl";
	namen[456] = "Smallrebel.com";
	namen[457] = "Sneakerbaas";
	namen[458] = "Sneeuwkettingen.com";
	namen[459] = "Sneltoner.nl";
	namen[460] = "Soccerfanshop.nl";
	namen[461] = "Soundmaster-shop.nl";
	namen[462] = "Speelgoedindeton.nl";
	namen[463] = "speelgoedpostorder";
	namen[464] = "SpiritHalloween.com";
	namen[465] = "Sport44.com";
	namen[466] = "Sportbay";
	namen[467] = "Sporthuis.nl";
	namen[468] = "Steps.nl";
	namen[469] = "Strijkpop.nl";
	namen[470] = "Stuntwinkel.nl";
	namen[471] = "Subsidesports.nl";
	namen[472] = "Sunjets";
	namen[473] = "SuperFout.nl";
	namen[474] = "Supersaver.nl";
	namen[475] = "Surprises-winkel.nl";
	namen[476] = "Sweetlivingshop";
	namen[477] = "Taartenwinkel.nl";
	namen[478] = "TableduSud.nl";
	namen[479] = "Tanga.com";
	namen[480] = "Tassen4jou.nl";
	namen[481] = "Tech66";
	namen[482] = "Tegeldepot.nl";
	namen[483] = "Telefoondiscounter.nl";
	namen[484] = "Telefoonhouderwinkel.nl";
	namen[485] = "Telegraaf";
	namen[486] = "Tennis-Geest";
	namen[487] = "TGV-europe.com";
	namen[488] = "Heineken The Sub";
	namen[489] = "Theorie-Examens.nl";
	namen[490] = "Thuisbezorgd.nl";
	namen[491] = "Thuiscursus.nl";
	namen[492] = "Timarco.nl";
	namen[493] = "Time4nutrition.nl";
	namen[494] = "TimeForTrends.nl";
	namen[495] = "TipTopDeal.nl";
	namen[496] = "Tiqqel.nl";
	namen[497] = "To-be-dressed.nl";
	namen[498] = "TomTom";
	namen[499] = "tomtom";
	namen[500] = "Tomtop.com";
	namen[501] = "TonerenCartridge.nl";
	namen[502] = "Tonershop.nl";
	namen[503] = "Tonerwinkel.nl";
	namen[504] = "Topbloemen.nl";
	namen[505] = "Touring Assurances / Verzekeringen";
	namen[506] = "Trainingspakken.nl";
	namen[507] = "Traveltroef.nl";
	namen[508] = "TuinGoedkoop.nl";
	namen[509] = "Tuinposter.be";
	namen[510] = "Tuintegelshop.nl";
	namen[511] = "TV Vlaanderen";
	namen[512] = "UltraDiamonds.com";
	namen[513] = "Unigro";
	namen[514] = "Uniqkleding";
	namen[515] = "Unisportstore.nl";
	namen[516] = "Usedpc4sale.nl";
	namen[517] = "Utsukusy";
	namen[518] = "Vacations Made Easy.com";
	namen[519] = "VakantieStunt.nl";
	namen[520] = "vanHaren";
	namen[521] = "VanKaarstotServet.nl";
	namen[522] = "Verandervanprovider.nl";
	namen[523] = "Verhuisdozensale.nl";
	namen[524] = "Verschoore";
	namen[525] = "Verstuureenbloemetje.nl";
	namen[526] = "HEMA verzekeringen";
	namen[527] = "Viabloemen.nl";
	namen[528] = "Viata.nl";
	namen[529] = "Videogames.nl";
	namen[530] = "Viking";
	namen[531] = "Vistaprint";
	namen[532] = "Vitacijn";
	namen[533] = "Vitamins.nl";
	namen[534] = "VitaZita.nl";
	namen[535] = "Vitstore.com";
	namen[536] = "Vivara";
	namen[537] = "ViveraWaterbedden.nl";
	namen[538] = "Vliegtickets.nl";
	namen[539] = "Vodafone";
	namen[540] = "Voetbal-Geest";
	namen[541] = "Voetbaldirect.be";
	namen[542] = "Voetbalfanwinkel.nl";
	namen[543] = "Voetbalhuis.nl";
	namen[544] = "Voetbalreizen.com";
	namen[545] = "Voetbalshirtjeswinkel.nl";
	namen[546] = "Voetbalshop.nl";
	namen[547] = "Voordeeldrogisterij.nl";
	namen[548] = "Voordeligscheren.nl";
	namen[549] = "Vrouwenvoetbalwebshop.nl";
	namen[550] = "Vuurwerkmania";
	namen[551] = "Wandel-Geest";
	namen[552] = "Wantsandneeds.nl";
	namen[553] = "Warentuin.nl";
	namen[554] = "Waschbär";
	namen[555] = "Wasmachine.nl";
	namen[556] = "Waterbedkampioen";
	namen[557] = "Watzalikkopen.nl";
	namen[558] = "WaySpa.com";
	namen[559] = "Wehkamp";
	namen[560] = "Wellnessbon.nl";
	namen[561] = "Wennekes";
	namen[562] = "Werkbroeken.nl";
	namen[563] = "Whinkel";
	namen[564] = "Whiteboardenstore";
	namen[565] = "Winter-Geest";
	namen[566] = "Witgoedhuis";
	namen[567] = "Woningisolatie-Vergelijken.nl";
	namen[568] = "Woon";
	namen[569] = "Wordpressking.nl";
	namen[570] = "SPAR Online";
	namen[571] = "Xandi.nl";
	namen[572] = "Xmasdeco.nl";
	namen[573] = "YourSurprise.nl";
	namen[574] = "Yves Rocher";
	namen[575] = "Yves Rocher";
	namen[576] = "Zalando";
	namen[577] = "Zandri.nl";
	namen[578] = "ZoGedrukt.nl";
	namen[579] = "Zooplus";
	namen[580] = "Zwembadexpress";
	namen[581] = "Zwemmershop";

	var hit = false;
	
	for (var i in sites) 
	{
	  if (document.location.href.indexOf(sites[i]) > -1)
	  {  	  	
	  	hit = getCookie("sponsorkliks");
	  	
	  	if (hit == null)
			{			  
			  setCookie("sponsorkliks","1",1);
				
				if (confirm(namen[i] + " bezoeken via Sponsorkliks, en met uw aankoop het Rotterdamsch Studenten Gezelschap  financieel steunen?"))
				{
					document.location = "http://www.sponsorkliks.com/partners.php?club=3831&v=website&shopsearch=" + encodeURI(namen[i]) + "&cn=NL&ln=nl";
				}
			}
	  	break;
		}
	}
    
});